<?php
//listing mappings
//66 items in array currently - 67 if db id is present
$listing = array(
"inData" => (int)1,
"AddressArea" => "LIST_29",
"AddressCity" => "LIST_39",
"AddressCountry" => "",
"AddressCounty" => "LIST_41",
"AddressDisplay" => "",
"AddressOneLine" => "",
"AddressStateOrProvince" => "LIST_40",
"AddressStreetDirPrefix" => "LIST_33",
"AddressStreetDirSuffix" => "LIST_36",
"AddressStreetName" => "LIST_34",
"AddressStreetNumber" => "LIST_31",
"AddressStreetSuffix" => "LIST_37",
"AddressUnitNumber" => "LIST_35",
"AllowIDX" => "LIST_104",
"Basement" => "LIST_157",
"BathsFull" => "LIST_68",
"BathsHalf" => "LIST_69",
"BathsOneQuarter" => (int)0,
"BathsThreeQuarter" => "LIST_70",
"BathsTotal" => "LIST_67",
"Bedrooms" => "LIST_66",
"DrivingDirections" => "LIST_141",
"ElementarySchool" => "LIST_112",
"GPSLatitude" => "LIST_46",
"GPSLongitude" => "LIST_47",
"HighSchool" => "LIST_114",
"ListingAgentEmail" => "listing_member_email",
"ListingAgentFirstname" => "",
"ListingAgentFullName" => "listing_member_name",
"ListingAgentID" => "LIST_5",
"ListingAgentLastName" => "",
"ListingAgentPhone1" => "listing_member_phone",
"ListingAgentPhone2" => "listing_office_phone",
"ListingAgentUrl" => "listing_member_url",
"ListingOfficeAddress" => "listing_office_address",
"ListingOfficeCity" => "",
"ListingOfficeID" => "LIST_106",
"ListingOfficeName" => "listing_office_name",
"ListingOfficeState" => "",
"ListPrice" => "LIST_22",
"ListStatus" => "LIST_15",
"ListType" => "LIST_8",
"LotSize" => "LIST_124",
"MiddleSchool" => "LIST_113",
"MLSName" => "",
"MLSNumber" => "LIST_3",
"ModificationTimestamp" => "LIST_87",
"OpenHousedate" => "",
"OpenHouseEnd" => "",
"OpenHouseStart" => "",
"Parking" => "LIST_122",
"PhotoCount" => "LIST_133",
"PhotoModificationTimestamp" => "LIST_134",
"PhotoUrls" => "",
"Pool" => "LIST_150",
"PostalCode" => "LIST_43",
"PropertyStyle" => "LIST_86",
"PublicRemarks" => "LIST_78",
"SchoolDistrict" => "",
"SquareFootage" => "LIST_48",
"Stories" => "LIST_120",
"TotalRooms" => "",
"TotalUnits" => "LIST_65",
"Waterfront" => "",
"YearBuilt" => "LIST_53",
);

$agent = array(
    "inData" => (int)1,
    "AgentID" => 'MEMBER_0',
    "AgentEmail" => 'MEMBER_10',
    "AgentFirstName" => 'MEMBER_3',
    "AgentFullName" => 'MEMBER_19',
    "AgentLastName" => 'MEMBER_4',
    "AgentPhone1" => 'MEMBER_6',
    "AgentPhone2" => 'MEMBER_7',
    "AgentUrl" => 'MEMBER_11',
    "MLSName" => $mls,
    "OfficeID" => 'MEMBER_1',
    "Timestamp" => 'TIMESTAMP'
);

$office = array(
    "inData" => (int)1,
    "MLS" => $mls,
    "OfficeAddress1" => 'OFFICE_10',
    "OfficeAddress2" => 'OFFICE_11',
    "OfficeCity" => 'OFFICE_12',
    "OfficeEmail" => 'OFFICE_8',
    "OfficeID" => 'OFFICE_0',
    "OfficeName" => 'OFFICE_2',
    "OfficePhone" => 'OFFICE_3',
    "OfficeState" => 'OFFICE13',
    "OfficeUnitNumber" => '',
    "OfficeZip" => 'OFFICE_14',
    "Timestamp" => 'TIMESTAMP'
);

?>
