<?php

//listing mappings
//for Matrix, will need a fair amount of customization
$listing = array(
"inData" => 1,
"AddressArea" => "L_Area",
"AddressCity" => "L_City",
"AddressCountry" => "",
"AddressCounty" => "LM_Char25_18",
"AddressOneLine" => "L_Address",
"AddressStateOrProvince" => "L_State",
"AddressStreetDirPrefix" => "L_AddressDirection",
"AddressStreetDirSuffix" => "Street_Post_Direction",
"AddressStreetName" => "L_AddressStreet",
"AddressStreetNumber" => "L_AddressNumber",
"AddressStreetSuffix" => "L_Address2",
"AddressUnitNumber" => "",
"AllowIDX" => "LV_vow_include",
"Basement" => "LFD_BASEMENT_6",
"BathsFull" => "LM_Dec_10",
"BathsHalf" => "LM_Dec_13",
"BathsOneQuarter" => "",
"BathsThreeQuarter" => "",
"BathsTotal" => "LM_Dec_1",
"Bedrooms" => "L_Keyword1",
"DrivingDirections" => "LM_char100_1",
"AddressDisplay" => "LV_vow_address",
"ElementarySchool" => "",
"GPSLatitude" => "LMD_MP_Latitude",
"GPSLongitude" => "LMD_MP_Longitude",
"HighSchool" => "",
"ListingAgentEmail" => "LA1_Email",
"ListingAgentFirstname" => "LA1_UserFirstName",
"ListingAgentFullName" => "",
"ListingAgentID" => "L_ListAgent1",
"ListingAgentLastName" => "LA1_UserLastName",
"ListingAgentPhone1" => "LA1_PhoneNumber1",
"ListingAgentPhone2" => "LA1_PhoneNumber2",
"ListingAgentUrl" => "LA1_WebPage",
"ListingOfficeAddress" => "",
"ListingOfficeCity" => "LO1_OrgCity",
"ListingOfficeID" => "L_ListOffice1",
"ListingOfficeName" => "LO1_OrganizationName",
"ListingOfficeState" => "LO1_OrgState",
"ListPrice" => "L_AskingPrice",
"ListStatus" => "L_StatusCatID",
"ListType" => "L_Class",
"LotSize" => "L_NumAcres",
"MiddleSchool" => "",
"MLSName" => "",
"MLSNumber" => "L_DisplayId",
"ModificationTimestamp" => "L_UpdateDate",
"OpenHousedate" => "",
"OpenHouseEnd" => "",
"OpenHouseStart" => "",
"Parking" => "L_Keyword",
"PhotoCount" => "L_PictureCount",
"PhotoModificationTimestamp" => "L_Last_Photo_updt",
"PhotoUrls" => "",
"Pool" => "",
"PostalCode" => "L_Zip",
"PropertyStyle" => "L_Type",
"PublicRemarks" => "L_Remarks",
"SchoolDistrict" => "",
"SquareFootage" => "L_SquareFeet",
"Stories" => "",
"TotalRooms" => "",
"TotalUnits" => "LM_Int4_4",
"Waterfront" => "L_Keyword10",
"YearBuilt" => "LM_int4_40",
);

$agent = array(
    "AgentID" => '',
    "AgentEmail" => '',
    "AgentPhone1" => '',
    "AgentPhone2" => '',
    "AgentUrl" => '',
    "MLS" => '',
    "OfficeID" => ''
);

$office = array(
    "MLS" => '',
    "OfficeAddress" => '',
    "OfficeEmail" => '',
    "OfficeID" => '',
    "OfficeName" => '',
    "OfficePhone" => '',
    "OfficeState" => '',
    "OfficeStreetname" => '',
    "OfficeStreetNumber" => '',
    "OfficeUnitNumber" => '',
    "OfficeZip" => ''
)

?>